package com.foodDelivaryApp.userservice.Enums;

public enum OfferTypeEnum {
    PERCENTAGE_DISCOUNT,
    FIXED_AMOUNT_DISCOUNT,
    BUY_ONE_GET_ONE,
    FREE_SHIPPING,
    BUNDLE_DISCOUNT,
    REWARD_POINTS,
    SPECIAL_OFFER,
    DIWALI_OFFER,
    EID_OFFER,
    SUMMER_SALE,
    CLEARANCE_SALE,
    FLASH_SALE,
    WEEKEND_SPECIAL,
    NEW_YEAR_OFFER,
    BLACK_FRIDAY,
    CYBER_MONDAY,
    CHRISTMAS_SALE;

}
